In [1]:
import pandas as pd
import glob
import os
import wfdb
# Define o padrão para os arquivos CSV

path = r'D:\cox-models-sudden-death\01_Dataset\dados_ECG\Holter_ECG\P0*'

#path = r'E:/Repositorio_Git/zzz-projeto_final/dados/ca-*.csv'


# Usando glob para pegar todos os arquivos que seguem o padrão
arquivos = glob.glob(path)
#arquivos_path_holter = glob.glob(path_holter)
arquivos = [os.path.splitext(arquivo)[0] for arquivo in arquivos] # tirando as a extensões





lista_sem_duplicatas = pd.Series(arquivos).unique().tolist() # removando duplicadas


record = wfdb.rdrecord(lista_sem_duplicatas[69])
record.__dict__

{'record_name': 'P0070',
 'n_sig': 2,
 'fs': 200,
 'counter_freq': None,
 'base_counter': None,
 'sig_len': 16476005,
 'base_time': None,
 'base_date': None,
 'comments': [],
 'sig_name': ['X', 'Y'],
 'p_signal': array([[ 0.  ,  0.  ],
        [ 0.  ,  0.  ],
        [ 0.  ,  0.  ],
        ...,
        [ 0.3 ,  1.6 ],
        [ 2.28,  1.58],
        [ 0.36, -0.34]]),
 'd_signal': None,
 'e_p_signal': None,
 'e_d_signal': None,
 'file_name': ['P0070.dat', 'P0070.dat'],
 'fmt': ['16', '16'],
 'samps_per_frame': [1, 1],
 'skew': [None, None],
 'byte_offset': [0, 0],
 'adc_gain': [100.0, 100.0],
 'baseline': [0, 0],
 'units': ['mV', 'mV'],
 'adc_res': [16, 16],
 'adc_zero': [0, 0],
 'init_value': [None, None],
 'checksum': [None, None],
 'block_size': [None, None]}

In [19]:
import pandas as pd

link_csv = r'D:\cox-models-sudden-death\01_Dataset\dados_csv_info_definitions\subject-info_formatado.csv'

df_info = pd.read_csv(link_csv, sep=';', header=0)

In [20]:
df_info

,Patient ID,Follow-up period from enrollment (days),days_4years,Exit of the study,Cause of death,SCD_4years SinusRhythm,HF_4years SinusRhythm,Age,Gender (male=1),Weight (kg),...,Angiotensin-II receptor blocker (yes=1),Anticoagulants/antitrombotics (yes=1),Betablockers (yes=1),Digoxin (yes=1),Loop diuretics (yes=1),Spironolactone (yes=1),Statins (yes=1),Hidralazina (yes=1),ACE inhibitor (yes=1),Nitrovasodilator (yes=1)
0,P0001,2065,1460,NaN,0,0,0,58,1,83,...,0,1,1,1,1,0,0,0,1,0
1,P0002,2045,1460,NaN,0,0,0,58,1,74,...,1,1,1,0,0,0,1,0,0,0
2,P0003,2044,1460,NaN,0,0,0,69,1,83,...,1,1,1,1,1,0,0,0,0,0
3,P0004,2044,1460,NaN,0,0,0,56,0,84,...,1,1,1,0,1,1,0,0,0,0
4,P0005,2043,1460,NaN,0,0,0,70,1,97,...,0,1,1,0,1,0,1,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
987,P1064,1393,1393,NaN,0,0,0,63,0,67,...,1,1,1,0,1,0,0,0,0,0
988,P1065,1393,1393,NaN,0,0,0,80,1,79,...,0,1,0,1,1,0,0,0,1,0
989,P1066,1387,1387,NaN,0,0,0,72,0,81,...,0,0,0,0,1,0,0,0,1,0
990,P1073,1365,1365,NaN,0,0,0,70,0,63,...,0,1,1,0,1,0,0,0,1,0
991,P1083,1624,1460,NaN,0,0,0,70,1,76,...,0,1,1,0,0,0,1,0,1,0

In [ ]:
link = r'D:\cox-models-sudden-death\02_Preprocessamento_filtro\resumo_dataset_ecg.csv'

df = pd.read_csv(link, sep=',')

In [22]:
df.head()

  paciente  n_canais  comprimento_sinal tem_X tem_Y tem_Z
0    P0001         3           16460600   Sim   Sim   Sim
1    P0002         3           16217800   Sim   Sim   Sim
2    P0003         3           15912600   Sim   Sim   Sim
3    P0004         3           15539200   Sim   Sim   Sim
4    P0005         3           15856000   Sim   Sim   Sim

In [23]:
# Filter patients where not all tem_X, tem_Y, tem_Z are "Sim"
df_lista = df[~((df['tem_X'] == 'Sim') & (df['tem_Y'] == 'Sim') & (df['tem_Z'] == 'Sim'))]

In [24]:
df_lista

    paciente  n_canais  comprimento_sinal tem_X tem_Y tem_Z
69     P0070         2           16476005   Sim   Sim   Não
121    P0125         2           12489750   Sim   Sim   Não
169    P0174         2           17278301   Sim   Sim   Não
238    P0247         2           17277894   Sim   Sim   Não
247    P0258         2           17277846   Sim   Sim   Não
290    P0302         2           17278079   Sim   Sim   Não
293    P0305         2           17277938   Sim   Sim   Não
297    P0310         2           17278846   Sim   Sim   Não
366    P0384         2           16765897   Sim   Sim   Não
398    P0421         2           17278035   Sim   Sim   Não
401    P0424         2           16634355   Sim   Sim   Não
402    P0425         2           14135384   Sim   Sim   Não
404    P0427         2           15830505   Sim   Sim   Não
416    P0448         2           17278273   Sim   Sim   Não
428    P0460         2           17277876   Sim   Sim   Não
430    P0462         2           17279377   Sim   Sim   Não
434    P0466         2           16500976   Sim   Sim   Não
455    P0489         2           17279313   Sim   Sim   Não
456    P0490         2           17277592   Sim   Sim   Não
458    P0493         2           17277892   Sim   Sim   Não
459    P0494         2           17277413   Sim   Sim   Não
460    P0495         2           17278979   Sim   Sim   Não
547    P0588         2           14892571   Sim   Sim   Não
551    P0592         2           14698875   Sim   Sim   Não
586    P0628         2           17279129   Sim   Sim   Não
619    P0661         2           17268007   Sim   Sim   Não
632    P0674         2           17268005   Sim   Sim   Não
661    P0706         2           14951552   Sim   Sim   Não
690    P0738         2           17277954   Sim   Sim   Não
743    P0792         2           17278191   Sim   Sim   Não
761    P0813         2           17277382   Sim   Sim   Não
762    P0814         2           17279729   Sim   Sim   Não
777    P0829         2           17278191   Sim   Sim   Não
778    P0831         2           17278118   Sim   Sim   Não
779    P0832         2           17277795   Sim   Sim   Não
839    P0898         2           17268007   Sim   Sim   Não
886    P0962         2           16403863   Sim   Sim   Não
935    P1073         2           14702765   Sim   Sim   Não

In [25]:
lista = df_lista['paciente'].to_list()

In [32]:
lista

['P0070',
 'P0125',
 'P0174',
 'P0247',
 'P0258',
 'P0302',
 'P0305',
 'P0310',
 'P0384',
 'P0421',
 'P0424',
 'P0425',
 'P0427',
 'P0448',
 'P0460',
 'P0462',
 'P0466',
 'P0489',
 'P0490',
 'P0493',
 'P0494',
 'P0495',
 'P0588',
 'P0592',
 'P0628',
 'P0661',
 'P0674',
 'P0706',
 'P0738',
 'P0792',
 'P0813',
 'P0814',
 'P0829',
 'P0831',
 'P0832',
 'P0898',
 'P0962',
 'P1073']

In [31]:
# Reload df_info with correct separator and header


df_info[df_info['Patient ID'].isin(lista)]

,Patient ID,Follow-up period from enrollment (days),days_4years,Exit of the study,Cause of death,SCD_4years SinusRhythm,HF_4years SinusRhythm,Age,Gender (male=1),Weight (kg),...,Angiotensin-II receptor blocker (yes=1),Anticoagulants/antitrombotics (yes=1),Betablockers (yes=1),Digoxin (yes=1),Loop diuretics (yes=1),Spironolactone (yes=1),Statins (yes=1),Hidralazina (yes=1),ACE inhibitor (yes=1),Nitrovasodilator (yes=1)
69,P0070,287,287,3.0,1,0,0,75,1,73,...,0,0,0,1,1,0,1,0,1,0
121,P0125,1966,1460,NaN,0,0,0,76,1,79,...,0,1,1,0,1,0,0,0,1,0
169,P0174,1960,1460,NaN,0,0,0,79,0,66,...,0,1,1,0,1,0,1,0,1,0
238,P0247,1949,1460,NaN,0,0,0,72,1,67,...,0,1,0,1,1,1,0,0,1,0
247,P0258,1945,1460,NaN,0,0,0,59,1,80,...,0,1,1,0,1,0,1,0,1,0
291,P0302,1919,1460,NaN,0,0,0,67,1,80,...,0,1,1,0,1,1,0,0,1,0
294,P0305,1919,1460,NaN,0,0,0,52,1,71,...,0,1,0,0,0,0,1,0,1,0
298,P0310,1919,1460,NaN,0,0,0,58,1,87,...,0,1,1,0,0,0,1,0,0,0
371,P0384,1940,1460,NaN,0,0,0,71,1,91,...,0,1,0,0,1,0,1,0,0,1
406,P0421,1880,1460,NaN,0,0,0,58,1,90,...,0,1,1,0,1,1,1,0,1,0
409,P0424,1889,1460,NaN,0,0,0,73,1,69,...,0,1,1,1,1,0,0,0,1,0
410,P0425,1889,1460,NaN,0,0,0,53,0,67,...,0,1,1,0,0,1,0,0,1,0
412,P0427,1882,1460,NaN,0,0,0,77,1,61,...,0,1,1,0,1,0,1,0,1,0
431,P0448,48,48,3.0,7,0,0,71,1,60,...,1,1,0,0,0,0,1,0,1,0
443,P0460,248,248,3.0,6,0,0,66,0,56,...,1,1,0,0,1,1,1,0,1,1
445,P0462,1867,1460,NaN,0,0,0,54,1,65,...,1,1,1,0,1,1,0,0,0,1
449,P0466,923,923,3.0,1,0,0,77,1,80,...,0,1,1,0,1,0,1,0,1,0
471,P0489,823,823,3.0,6,0,1,52,1,76,...,0,1,1,1,1,1,0,0,1,0
472,P0490,1861,1460,NaN,0,0,0,74,1,85,...,0,1,1,0,1,1,0,0,1,1
474,P0493,1861,1460,NaN,0,0,0,67,1,80,...,0,1,1,0,0,0,1,0,0,0
475,P0494,87,87,3.0,3,1,0,71,1,82,...,0,1,1,0,0,0,1,0,0,1
476,P0495,1861,1460,NaN,0,0,0,47,1,89,...,0,1,1,0,1,0,1,0,1,0
566,P0588,1849,1460,NaN,0,0,0,77,1,92,...,0,1,0,1,1,0,0,0,1,1
570,P0592,1847,1460,NaN,0,0,0,66,1,78,...,0,1,1,1,1,1,1,0,0,0
605,P0628,1833,1460,NaN,0,0,0,68,0,94,...,0,1,1,1,1,0,1,0,1,0
638,P0661,184,184,3.0,3,1,0,67,0,65,...,0,0,1,1,0,1,0,0,1,0
651,P0674,1826,1460,NaN,0,0,0,66,1,71,...,0,1,0,0,1,0,0,0,1,0
681,P0706,1842,1460,NaN,0,0,0,72,1,69,...,0,1,1,1,0,0,0,0,1,1
712,P0738,1785,1460,NaN,0,0,0,70,0,74,...,1,1,1,0,0,0,1,0,1,0
766,P0792,528,528,3.0,6,0,0,85,1,86,...,0,1,1,1,1,1,0,0,0,1
785,P0813,1756,1460,NaN,0,0,0,67,1,65,...,0,1,1,0,0,0,1,0,1,1
786,P0814,1756,1460,NaN,0,0,0,72,0,90,...,1,1,1,0,1,1,1,0,0,0
801,P0829,1749,1460,NaN,0,0,0,60,0,97,...,1,0,0,1,0,0,0,0,0,0
803,P0831,1748,1460,NaN,0,0,0,66,0,103,...,0,1,0,0,1,1,1,0,1,0
804,P0832,1748,1460,NaN,0,0,0,56,1,94,...,0,0,1,0,1,1,0,0,1,0
866,P0898,389,389,3.0,3,1,0,67,1,85,...,0,1,0,0,1,1,0,0,1,1
922,P0962,1724,1460,NaN,0,0,0,55,1,105,...,0,1,1,1,1,1,0,1,0,1
990,P1073,1365,1365,NaN,0,0,0,70,0,63,...,0,1,1,0,1,0,0,0,1,0

In [ ]:
df_info[df_info['Patient ID'] == lista]